import type { CompanyDTO } from '../types.js';
export const companyRegistry: CompanyDTO[] = [
  { name: 'Google', website: 'https://google.com', careerUrl: 'https://careers.example.com/google', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Microsoft', website: 'https://microsoft.com', careerUrl: 'https://careers.example.com/microsoft', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Amazon', website: 'https://amazon.com', careerUrl: 'https://careers.example.com/amazon', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Meta', website: 'https://meta.com', careerUrl: 'https://careers.example.com/meta', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Apple', website: 'https://apple.com', careerUrl: 'https://careers.example.com/apple', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Netflix', website: 'https://netflix.com', careerUrl: 'https://careers.example.com/netflix', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Adobe', website: 'https://adobe.com', careerUrl: 'https://careers.example.com/adobe', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Salesforce', website: 'https://salesforce.com', careerUrl: 'https://careers.example.com/salesforce', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Oracle', website: 'https://oracle.com', careerUrl: 'https://careers.example.com/oracle', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'IBM', website: 'https://ibm.com', careerUrl: 'https://careers.example.com/ibm', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Cisco', website: 'https://cisco.com', careerUrl: 'https://careers.example.com/cisco', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'VMware', website: 'https://vmware.com', careerUrl: 'https://careers.example.com/vmware', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Atlassian', website: 'https://atlassian.com', careerUrl: 'https://careers.example.com/atlassian', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'ServiceNow', website: 'https://servicenow.com', careerUrl: 'https://careers.example.com/servicenow', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Intuit', website: 'https://intuit.com', careerUrl: 'https://careers.example.com/intuit', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'PayPal', website: 'https://paypal.com', careerUrl: 'https://careers.example.com/paypal', industry: 'Fintech', country: 'US', indiaPresence: true, active: true },
  { name: 'Mastercard', website: 'https://mastercard.com', careerUrl: 'https://careers.example.com/mastercard', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Visa', website: 'https://visa.com', careerUrl: 'https://careers.example.com/visa', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'American Express', website: 'https://americanexpress.com', careerUrl: 'https://careers.example.com/american-express', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'JPMorgan Chase', website: 'https://jpmorganchase.com', careerUrl: 'https://careers.example.com/jpmorgan-chase', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Goldman Sachs', website: 'https://goldmansachs.com', careerUrl: 'https://careers.example.com/goldman-sachs', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Morgan Stanley', website: 'https://morganstanley.com', careerUrl: 'https://careers.example.com/morgan-stanley', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Walmart Global Tech', website: 'https://walmartglobaltech.com', careerUrl: 'https://careers.example.com/walmart-global-tech', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Target', website: 'https://target.com', careerUrl: 'https://careers.example.com/target', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Uber', website: 'https://uber.com', careerUrl: 'https://careers.example.com/uber', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Airbnb', website: 'https://airbnb.com', careerUrl: 'https://careers.example.com/airbnb', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Booking', website: 'https://booking.com', careerUrl: 'https://careers.example.com/booking', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'SAP', website: 'https://sap.com', careerUrl: 'https://careers.example.com/sap', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Siemens', website: 'https://siemens.com', careerUrl: 'https://careers.example.com/siemens', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Bosch', website: 'https://bosch.com', careerUrl: 'https://careers.example.com/bosch', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Accenture', website: 'https://accenture.com', careerUrl: 'https://careers.example.com/accenture', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Infosys', website: 'https://infosys.com', careerUrl: 'https://careers.example.com/infosys', industry: 'Technology', country: 'India', indiaPresence: true, active: true },
  { name: 'TCS', website: 'https://tcs.com', careerUrl: 'https://careers.example.com/tcs', industry: 'Technology', country: 'India', indiaPresence: true, active: true },
  { name: 'Wipro', website: 'https://wipro.com', careerUrl: 'https://careers.example.com/wipro', industry: 'Technology', country: 'India', indiaPresence: true, active: true },
  { name: 'HCL', website: 'https://hcl.com', careerUrl: 'https://careers.example.com/hcl', industry: 'Technology', country: 'India', indiaPresence: true, active: true },
  { name: 'Cognizant', website: 'https://cognizant.com', careerUrl: 'https://careers.example.com/cognizant', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Capgemini', website: 'https://capgemini.com', careerUrl: 'https://careers.example.com/capgemini', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Thoughtworks', website: 'https://thoughtworks.com', careerUrl: 'https://careers.example.com/thoughtworks', industry: 'Technology', country: 'US', indiaPresence: true, active: true },
  { name: 'Flipkart', website: 'https://flipkart.com', careerUrl: 'https://careers.example.com/flipkart', industry: 'Technology', country: 'India', indiaPresence: true, active: true },
  { name: 'PhonePe', website: 'https://phonepe.com', careerUrl: 'https://careers.example.com/phonepe', industry: 'Fintech', country: 'India', indiaPresence: true, active: true },
  { name: 'Razorpay', website: 'https://razorpay.com', careerUrl: 'https://careers.example.com/razorpay', industry: 'Fintech', country: 'India', indiaPresence: true, active: true },
  { name: 'CRED', website: 'https://cred.com', careerUrl: 'https://careers.example.com/cred', industry: 'Fintech', country: 'India', indiaPresence: true, active: true },
  { name: 'Groww', website: 'https://groww.com', careerUrl: 'https://careers.example.com/groww', industry: 'Fintech', country: 'India', indiaPresence: true, active: true },
  { name: 'Zerodha', website: 'https://zerodha.com', careerUrl: 'https://careers.example.com/zerodha', industry: 'Fintech', country: 'India', indiaPresence: true, active: true },
  { name: 'Navi', website: 'https://navi.com', careerUrl: 'https://careers.example.com/navi', industry: 'Fintech', country: 'India', indiaPresence: true, active: true },
  { name: 'Meesho', website: 'https://meesho.com', careerUrl: 'https://careers.example.com/meesho', industry: 'Technology', country: 'India', indiaPresence: true, active: true },
  { name: 'Freshworks', website: 'https://freshworks.com', careerUrl: 'https://careers.example.com/freshworks', industry: 'Technology', country: 'India', indiaPresence: true, active: true },
  { name: 'Zoho', website: 'https://zoho.com', careerUrl: 'https://careers.example.com/zoho', industry: 'Technology', country: 'India', indiaPresence: true, active: true }
];
