import type { FilterQuery, SortOrder, Types } from 'mongoose';
import { JobModel } from '../models/job.model.js';
import type { JobDTO, JobFilters, PaginatedResult } from '../types.js';
export class JobRepository {
  async findDuplicate(candidate: Pick<JobDTO, 'companyId' | 'jobId' | 'title' | 'location' | 'applyUrl'>): Promise<JobDTO | null> { return JobModel.findOne({ $or: [{ companyId: candidate.companyId, jobId: candidate.jobId }, { title: candidate.title, location: candidate.location, applyUrl: candidate.applyUrl }] }).lean(); }
  async upsert(job: JobDTO): Promise<{ item: JobDTO; created: boolean }> { const existing = await this.findDuplicate(job); if (existing?._id) { const updated = await JobModel.findByIdAndUpdate(existing._id, { $set: { ...job, lastSeenAt: new Date(), isActive: true } }, { new: true }).lean(); return { item: updated as JobDTO, created: false }; } const created = await JobModel.create(job); return { item: created.toObject(), created: true }; }
  async findById(id: string): Promise<JobDTO | null> { return JobModel.findById(id).populate('companyId', 'name industry website careerUrl').lean(); }
  async list(filters: JobFilters): Promise<PaginatedResult<JobDTO>> { const query = this.buildQuery(filters); const sort: Record<string, SortOrder> = { [filters.sortBy]: filters.sortOrder === 'asc' ? 1 : -1 }; const skip = (filters.page - 1) * filters.limit; const [items, total] = await Promise.all([JobModel.find(query).populate('companyId', 'name industry').sort(sort).skip(skip).limit(filters.limit).lean(), JobModel.countDocuments(query)]); return { items, page: filters.page, limit: filters.limit, total, totalPages: Math.ceil(total / filters.limit) }; }
  async stats(): Promise<Record<string, unknown>> { const [totalJobs, byCompany, byCity, byExperience, recentlyAdded, topHiringCompanies] = await Promise.all([JobModel.countDocuments({ isActive: true }), JobModel.aggregate([{ $match: { isActive: true } }, { $group: { _id: '$companyId', count: { $sum: 1 } } }, { $lookup: { from: 'companies', localField: '_id', foreignField: '_id', as: 'company' } }, { $unwind: '$company' }, { $project: { name: '$company.name', count: 1, _id: 0 } }, { $sort: { count: -1, name: 1 } }]), JobModel.aggregate([{ $match: { isActive: true } }, { $group: { _id: '$location', count: { $sum: 1 } } }, { $project: { city: '$_id', count: 1, _id: 0 } }, { $sort: { count: -1 } }, { $limit: 20 }]), JobModel.aggregate([{ $match: { isActive: true } }, { $group: { _id: { min: '$experienceMin', max: '$experienceMax' }, count: { $sum: 1 } } }, { $project: { range: { $concat: [{ $toString: '$_id.min' }, '-', { $toString: '$_id.max' }, ' years'] }, count: 1, _id: 0 } }, { $sort: { range: 1 } }]), JobModel.find({ isActive: true }).populate('companyId', 'name').sort({ createdAt: -1 }).limit(10).lean(), JobModel.aggregate([{ $match: { isActive: true } }, { $group: { _id: '$companyId', count: { $sum: 1 } } }, { $lookup: { from: 'companies', localField: '_id', foreignField: '_id', as: 'company' } }, { $unwind: '$company' }, { $project: { name: '$company.name', count: 1, _id: 0 } }, { $sort: { count: -1 } }, { $limit: 10 }])]); return { totalJobs, byCompany, byCity, byExperience, recentlyAdded, topHiringCompanies }; }
  async markStaleInactive(syncStartedAt: Date): Promise<number> { const result = await JobModel.updateMany({ lastSeenAt: { $lt: syncStartedAt }, isActive: true }, { $set: { isActive: false } }); return result.modifiedCount; }
  async findForExport(filters: JobFilters): Promise<JobDTO[]> { return JobModel.find(this.buildQuery(filters)).populate('companyId', 'name').sort({ postedDate: -1, createdAt: -1 }).limit(10000).lean(); }
  private buildQuery(filters: JobFilters): FilterQuery<JobDTO> { const query: FilterQuery<JobDTO> = { isActive: true }; if (filters.search) query.$text = { $search: filters.search }; if (filters.companyId) query.companyId = filters.companyId as unknown as Types.ObjectId; if (filters.location) query.location = new RegExp(filters.location, 'i'); if (filters.skill) query.skills = { $regex: filters.skill, $options: 'i' }; if (filters.experienceMin !== undefined) query.experienceMax = { $gte: filters.experienceMin }; if (filters.experienceMax !== undefined) query.experienceMin = { $lte: filters.experienceMax }; if (filters.postedFrom || filters.postedTo) { query.postedDate = {}; if (filters.postedFrom) query.postedDate.$gte = filters.postedFrom; if (filters.postedTo) query.postedDate.$lte = filters.postedTo; } return query; }
}
