import { CompanyRepository } from '../repositories/company.repository.js';
import { JobHistoryRepository } from '../repositories/jobHistory.repository.js';
import { JobRepository } from '../repositories/job.repository.js';
import type { JobDTO, ProviderJobInput } from '../types.js';
import { logger } from '../utils/logger.js';
import { ProviderFactory } from '../integrations/providers/providerFactory.js';
import { CompanyService } from './company.service.js';
import { JobMatchingService } from './jobMatching.service.js';
export interface SyncResult { fetched: number; matched: number; created: number; updated: number; deactivated: number; providers: number; }
export class JobIngestionService { constructor(private readonly jobRepository = new JobRepository(), private readonly companyRepository = new CompanyRepository(), private readonly historyRepository = new JobHistoryRepository(), private readonly matchingService = new JobMatchingService(), private readonly companyService = new CompanyService(companyRepository)) {} async syncAll(): Promise<SyncResult> { const syncStartedAt = new Date(); await this.companyService.seedRegistry(); const providers = ProviderFactory.createProviders(); let fetched = 0, matched = 0, created = 0, updated = 0; for (const provider of providers) { const providerJobs = await provider.fetchJobs(); fetched += providerJobs.length; for (const providerJob of providerJobs) { if (!this.matchingService.isTargetJob(providerJob)) continue; matched += 1; const company = await this.companyRepository.findByName(providerJob.companyName); if (!company?._id) { logger.warn('Skipping job because company is not registered', { companyName: providerJob.companyName }); continue; } const result = await this.jobRepository.upsert(this.normalize(providerJob, String(company._id))); if (result.created) created += 1; else updated += 1; if (result.item._id) await this.historyRepository.record(String(result.item._id), result.created ? 'created' : 'seen'); } } const deactivated = await this.jobRepository.markStaleInactive(syncStartedAt); logger.info('Job sync completed', { fetched, matched, created, updated, deactivated, providers: providers.length }); return { fetched, matched, created, updated, deactivated, providers: providers.length }; } private normalize(job: ProviderJobInput, companyId: string): JobDTO { return { ...job, companyId, title: job.title.trim(), location: job.location.trim(), skills: this.matchingService.extractSkills(job), postedDate: job.postedDate ? new Date(job.postedDate) : new Date(), lastSeenAt: new Date(), isActive: true }; } }
